# Site settings
title: Центр подводного плавания Аквастиль 
email: info@aquastyl74.ru
description: >
  В нашем дайвинг-центре вы можете пройти обучение дайвингу 
  под руководством опытных инструкторов. Зимой занятия по дайвингу проводятся
  в бассейне «Юбилейный», ул.40 лет Октября 31а.
  Летом обучения дайвингу проходят на озере Увильды, база отдыха «Янтарь».
baseurl: ""
url: "http://aqst.summerisgone.com"

image:
  source: images
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    half:
      width: 400
      height: AUTO

# Build settings
markdown: kramdown